// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:app_drink_more_water/models/daily_goal_model.dart';
import 'package:app_drink_more_water/models/water_intake_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyGoalAdapter());
    registerAdapter(WaterIntakeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyGoalAdapter());
    registerAdapter(WaterIntakeAdapter());
  }
}
